# action.yml
name: 'lazy-action-dotnet'
description: 'Github action to perform build, test , scan and generate image.'
inputs:
  src_file_dir:  # source file directory
    description: 'Source file directory'
    required: true
    default: './'
  dockerfile_dir:  # docker file directory
    description: 'Dockerfile  directory'
    required: true
  github_token:  # github owner token
    description: 'Github token'
    required: true
  github_owner_token:  # github owner token
    description: 'Github owner token'
    required: true
  sonar_token:  # sonar token
    description: 'Github token'
    required: true
  dev_aws_account_id:  # dev aws account id
    description: 'Dev AWS Account ID'
    required: true 
  aws_access_key_id:  # aws access key id
    description: 'AWS access key'
    required: true
  aws_secret_access_key:  # aws secret access key
    description: 'AWS secret access key'
    required: true
  aws_region:  # aws region
    description: 'AWS Region'
    required: false
    default: 'us-east-2'
  docker_repo_name:  # docker repo name 
    description: 'Docker repo name'
    required: true
  docker_image_name:  # docker image name 
    description: 'Docker image name'
    required: true
  sonar_project_key:  #  sonar project key
    description: 'Sonar Project Key'
    required: false
    default: 'variant-inc'
  sonar_org:  # sonar organization
    description: 'Sonar organization'
    required: false
    default: 'ariant'
  sonar_scan_enabled:  # sonar scan enabled
    description: 'To check sonar scan needed.'
    required: true
  nuget_push:  # build publish
    description: 'build publish'
    required: true
  docker_push:  # docker push
    description: 'docker push'
    required: true


runs:
  using: 'docker'
  image: docker://public.ecr.aws/p4v7w0a5/lazy/donet-base
  env:
    SOURCE_FILE_PATH: ${{ inputs.src_file_dir }} 
    CUSTOM_DOCKER_FILE_PATH: ${{ inputs.dockerfile_dir }} 
    GITHUB_USER: $GITHUB_ACTOR
    GITHUB_TOKEN: ${{ inputs.github_token }} 
    GITHUB_OWNER: $OWNER
    GITHUB_OWNER_TOKEN: ${{ inputs.github_owner_token }} 
    DEV_AWS_ACCOUNT_ID: ${{ inputs.dev_aws_account_id }}
    AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }} 
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }} 
    AWS_DEFAULT_REGION: ${{ inputs.aws_region }} 
    DOCKER_REPO_NAME: ${{ inputs.docker_repo_name }} 
    DOCKER_IMAGE_NAME: ${{ inputs.docker_image_name }} 
    SONARCLOUD_PROJECT_KEY: ${{ inputs.sonar_project_key }} 
    SONAR_ORG: ${{ inputs.sonar_org }} 
    SONAR_SCAN_ENABLED: ${{ inputs.sonar_scan_enabled }} 
    NUGET_PUSH: ${{ inputs.nuget_push }} 
    DOCKER_PUSH: ${{ inputs.docker_push }} 
