# action.yml
name: "lazy-action-dotnet"
description: "Github action to perform build, test , scan and generate image."
inputs:
  src_file_dir_path: # source file directory path
    description: "Path to the directory which contains the solution file"
    required: true
    default: "."
  dockerfile_dir_path:
    description: "Path to Dockerfile"
    required: true
    default: "."
  github_token: # github owner token
    description: "Github token"
    required: true
  ecr_repository_region: # aws region
    description: "ECR Repository Region"
    required: false
    default: "us-east-1"
  ecr_repository: # docker image name
    description: "Docker image name"
    required: true
  sonar_project_key: #  sonar project key
    description: "Sonar Project Key"
    required: false
    default: "variant-inc"
  sonar_scan_enabled: # sonar scan enabled
    description: "To check sonar scan needed."
    required: true
    default: "true"
  nuget_push_enabled: # build publish
    description: "Build and Push Nuget Packages"
    required: false
    default: "false"
  nuget_src_folder:
    description: "Path to the Nuget src folder"
    required: false
  container_push_enabled: # docker push
    description: "Build and Push Container Image"
    required: false
    default: "true"

runs:
  using: "docker"
  image: docker://public.ecr.aws/p4v7w0a5/lazy/donet-base
  env:
    GITHUB_USER: $GITHUB_ACTOR
    GITHUB_TOKEN: ${{ inputs.github_token }}
