# action.yml
name: "Lazy Action Dotnet"
description: "Github action to perform build, test , scan and generate image."
inputs:
  src_file_dir_path:
    description: "Directory path to the solution file"
    required: true
    default: "."
  dockerfile_dir_path:
    description: "Directory path to the dockerfile"
    required: true
  ecr_repository:
    description: "Ecr repository name."
    required: true
  sonar_scan_in_docker:
    description: "Is sonar scan running as part of Dockerfile."
    required: false
    default: "false"
  sonar_scan_in_docker_target:
    description: "sonar scan in docker target"
    required: false
    default: "sonarscan-env"
  nuget_push_enabled:
    description: "Enabled Nuget Push to Package Registry."
    required: false
    default: "false"
  nuget_package_name:
    description: "Creates the nuget package with this name.Used only when nuget_push_enabled is true."
    required: false
  nuget_project_path:
    description: "Path to the Nuget Project File (.csproj).Used only when nuget_push_enabled is true.Required if nuget_push_enabled is true."
    required: false
  container_push_enabled:
    description: "Enable Build and Push Container Image"
    required: false
    default: "true"
  github_token:
    description: "Github token"
    required: true


runs:
  using: "docker"
  image: docker://public.ecr.aws/p4v7w0a5/lazy/dotnet-action:sha-76625f396f9aad86b46621d548d6abd6eccc26c9
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}