# action.yml
name: "Lazy Action Dotnet"
description: "Github action to perform build, test , scan and generate image."
inputs:
  src_file_dir_path:
    description: "Directory path to the solution file"
    required: true
    default: "."
  dockerfile_dir_path:
    description: "Directory path to the dockerfile"
    required: true
  ecr_repository:
    description: "Ecr repository name"
    required: true
  sonar_scan_in_docker:
    description: "Is sonar scan running as part of Dockerfile"
    required: false
    default: "false"
  sonar_scan_in_docker_target:
    description: "sonar scan in docker target"
    required: false
    default: "sonarscan-env"
  nuget_push_enabled:
    description: "If nuget push enabled to package registry. Set this value to true."
    required: false
    default: "false"
  nuget_package_name:
    description: "Use only if nuget_push_enabled is enabled and want to give nuget pacakage name.By default, it will be the name of the project."
    required: false
  nuget_src_project:
    description: "Use only if nuget_push_enabled is enabled Path to the nuget project file (.csproj)"
    required: false
  container_push_enabled:
    description: "Enable Build and Push Container Image"
    required: false
    default: "true"
  github_token:
    description: "Github token"
    required: true


runs:
  using: "docker"
  image: docker://public.ecr.aws/p4v7w0a5/lazy/dotnet-action:v1
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}